schemaVersion: 2.1.0
metadata:
  name: toolbox
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
  - name: devtools
    container:
      image: gcr.io/google-containers/toolbox:latest
      memoryLimit: 2Gi
      memoryRequest: 256Mi
